# Generated by Django 3.0.8 on 2020-08-22 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsstory',
            name='image_url',
            field=models.CharField(default='https://www.sl-inspiration.com/2014/08/creating-anumated-gifs-for-second-life.html', max_length=200),
        ),
    ]
